apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: kadekpradnyana/bonsai-auth-mgmt
          env:
            - name: SERVICE_USER_HOST
              value: "user-service"
            - name: SERVICE_USER_PORT
              value: "4010"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: rpc
      protocol: TCP
      port: 4000
      targetPort: 4000
